### PR TITLE
Mention that quora.vern.cc is now rate limited

### PR DESCRIPTION
**Pull request by gi-yt**

### CODE REVIEW

**Comment by zyachel** [comment]
I knew that sooner or later it'll happen. :/

How much traffic is there on your instance, @gi-yt?

**Comment by gi-yt** [comment]
not sure since we dont keep any access logs...

**Comment by gi-yt** [comment]
i dont think the heroku one should be affected since from what i understand server keeps changing ?

**Comment by zyachel** [comment]
> i dont think the heroku one should be affected since from what i understand server keeps changing ?

I'm not sure but I think they do recycle IP addresses.  


When I get time, I'll look for(and learn) a way to avoid being rate-limited. Right now, even the responses aren't being cached. So, just going back triggers a request to Quora, which isn't ideal.

**Comment by gi-yt** [comment]
i think the issue was our status.vern.cc page since it was querying a quora question via quora.vern.cc every 60 seconds... i have set the time to 3600 seconds but we already got ratelimited again :P

**Comment by gi-yt** [comment]
@zyachel it still happened. my final solution is basically blocking farside.link, since it checks whether frontend works too often..
```
if ($http_user_agent = "Mozilla/5.0 (compatible; Farside/0.1.0; +https://farside.link)"){
return 403;
}
```

**Comment by zyachel** [comment]
@gi-yt, perhaps we should talk to the author of farside first? I don't think blocking is the best way since farside isn't a rogue bot. Though in case of Quetre, it often causes Quora to ratelimit the instances.

**Pull request merged**
