### PR TITLE
Add docker-compose.yml & image-publish.yml workflow  

### PR DESCRIPTION
**Pull request by alefvanoon**
Hello, I have added everything needed for Docker setup.
For both arm64 and amd64 architectures.
I tested it on arm64.

### CODE REVIEW

**Comment by alefvanoon** [comment]
https://github.com/users/alefvanoon/packages/container/package/quetre

**Comment by zyachel** [comment]
hey there!  

thanks a lot for this. Will a description in the README be helpful? If so, can you add that as well?  

Because, frankly, I know nothing about how this will be used. Do you run this command ``docker pull ghcr.io/alefvanoon/quetre:main``(and maybe ``docker run`` afterwards)?

**Comment by zyachel** [comment]
Thanks!

**Comment by alefvanoon** [comment]
All you need to do after merging is to get a GitHub token with the ability to write package.
https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token

And after every update, you should go to https://github.com/zyachel/quetre/actions and publish the new image.
image

**Comment by alefvanoon** [comment]
> Same as [zyachel/libremdb#7](https://github.com/zyachel/libremdb/pull/7)
> 
> @alefvanoon @zyachel I never allowed you to re-license my work.
> 
> Respect the license. https://github.com/PussTheCat-org/docker-quetre-quay
> 
> It's the second time a project I made an image for steal my work, at this point I'll just stop publishing my docker image publicly.

I will remove and rewrite the parts of your code that I used.
Sorry.

**Comment by TheFrenchGhosty** [comment]
@zyachel You either have to make the project respect the files license, or force push the commits out.

**Comment by alefvanoon** [comment]
#18

**Comment by zyachel** [comment]
@TheFrenchGhosty, sorry, I had no idea it was your image. I presumed @alefvanoon made it himself.
Regardless, if you think latest pull doesn't correct it, let me know, I'll remove docker ability entirely till I learn to make one by myself.

> it's the second time a project I made an image for steal my work, at this point I'll just stop publishing my docker image publicly.

Again, it was never my intention to disregard your work or license. So, please don't take any definitive decision regarding the incident. You have done great amount of work for this and many similar projects, and I appreciate it.

**Comment by TheFrenchGhosty** [comment]
@zyachel  

This isn't against you, you didn't do it on purpose, though, you should have reviewer the PR in a deeper way.

>Regardless, if you think latest pull doesn't correct it, let me know, I'll remove docker ability entirely till I learn to make one by myself.

Your relicensing apply to the whole source tree (meaning previous commits are affected), as I said before, you have to "force push the commits out" (or properly respect the license)

**Comment by zyachel** [comment]
alright, I'll hard reset the commits. Will that do the job?

And yes, I should've reviewed the pull. I'll take care next time.

**Comment by TheFrenchGhosty** [comment]
@zyachel Yes, hard reset will do.

**Comment by zyachel** [comment]
@TheFrenchGhosty, done. Is it okay now?

Again, sorry for that. I hope you aren't too upset about it.

**Comment by TheFrenchGhosty** [comment]
@zyachel Yes, perfect.

**Pull request merged**
