### PR TITLE
add habedieeh.re instance

### PR DESCRIPTION
**Pull request by shruuub**
adds clearnet habedieeh.re instance as well as it's tor instance. Tor seems broken though, at all instances.

### CODE REVIEW

**Comment by zyachel** [comment]
did you try adding ``NO_UPGRADE=1`` for tor in ``.env``?

**Comment by shruuub** [comment]
> did you try adding `NO_UPGRADE=1` for tor in `.env`?

No, will do that now. I use the image by TheFrenchGhosty, but I suppose that will work the same

**Comment by shruuub** [comment]
coolio, that worked! Instance fully works now, ready to be added.

**Comment by zyachel** [comment]
sweet!

**Pull request merged**
