### PR TITLE
Remove quetre.catsarch.com

### PR DESCRIPTION
**Pull request by ButteredCats**
I always seem to be rate limited every time I try and access something via Quetre. This makes my instance pretty useless and Quora totally inaccessible from my house since my server is on the same network as me.

I'm totally up for suggestions if there are ways to fix it as I didn't really wanna go this route, today was just the day that I finally got sick of being totally barred from the site.

I won't shut it down until this is merged in case something can be done about this.

Either way, thank you all your work on Quetre.

### CODE REVIEW

**Comment by zyachel** [comment]
I understand. apart from using redis, there's not much you can do. I mean, there are ways, but quora is dead anyway.

**Comment by zyachel** [comment]
you forgot to remove the entry from README

**Comment by ButteredCats** [comment]
My bad, hopefully all is good now.

**Comment by zyachel** [comment]
done, thanks!

**Pull request closed without merging**
