### PR TITLE
Mark unanswered (related) questions

### LINKED ISSUE #54: Mark unanswered questions
We could mark an unanswered question by putting "Unanswered" to the right and in gold color (for example).

### PR DESCRIPTION
**Pull request by thecashewtrader**
closes #54.

Note: I'm not sure about the need of `+spansChecker`, but someone else can comment better on that.

### CODE REVIEW

**Comment by zyachel** [comment]
some questions contain tex that needs to be worked on before being picked up by MathJax. that's why there's `+spansChecker` for them.

**Comment by thecashewtrader** [comment]
Could you give me an example so I can work on a better implementation?

**Comment by zyachel** [comment]
this has some good examples: `http://localhost:3000/How-do-you-compute-the-Fourier-transform-for-exp-alpha-t-2`

**Comment by thecashewtrader** [comment]
@NebulaOnion #92 should work hopefully!

**Pull request closed without merging**
